baseURL = "https://uhourri.github.io/"
languageCode = "en-us"
title = "Youness Hourri â€“ Researcher in Software Engineering & Open Source"
theme = "PaperMod"

[params]
  author = "Youness Hourri"
  description = "My professional and academic portfolio"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowToc = true # Enables table of contents for longer posts

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "academia"
    name = "Academia"
    url = "/academia/"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4